# Generated by Django 3.2.3 on 2021-10-14 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_visits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='visits',
        ),
    ]
